### ISSUE TITLE
property nread does not exist on type number

### ISSUE THREAD

**Issue by dpremus** [manyuanrong/deno_mysql#13]
Hi

I'm trying to import deno_mysql library but I got these error:

←[1;31merror←[0m←[1m TS2339←[0m: Property 'nread' does not exist on type 'number'.
←[38;5;14mhttps://deno.land/x/mysql/src/packets/packet.ts←[0m:←[38;5;11m44←[0m:←[38;5;11m1

deno version: 0.12.0  v8: 7.7.200  typescript: 3.5.1
tested on win7 with power shell

code that reproduce this error: 

import { Client } from "https://deno.land/x/mysql/mod.ts";

Regards

Danijel

**Comment by manyuanrong** [comment]
@dpremus 
I upgraded the Deno version to 0.12.0 to solve this problem.

**Comment by dpremus** [comment]
Thank you 
everything works fine
