### ISSUE TITLE
Query doesn't return last row when accessing MariaDB

### ISSUE THREAD

**Issue by dpremus** [manyuanrong/deno_mysql#14]
Hi,

The last record is missing when accessing MariaDB.

Problem is in method "connection.execute()" in "module connection.ts"
this part of code:

 if (this.serverVersion < "5.7.0") {
      // EOF(less than 5.7)
      receive = await this.nextPacket();
    }

MariaDB returns "serverVersion" 5.5.5-10.4.7-MariaDB

Here is my fix:

    if ((this.serverVersion < "5.7.0") && (this.serverVersion.substr(this.serverVersion.length - 8) != "-MariaDB")) {
      // EOF(less than 5.7)
      receive = await this.nextPacket();
    }

Best Regards

Danijel

**Comment by delwiv** [comment]
I made a PR that addresses this issue [#18](https://github.com/manyuanrong/deno_mysql/pull/18)
