### ISSUE TITLE
What is difference between execute and query?

### ISSUE THREAD

**Issue by magichim** [manyuanrong/deno_mysql#20]
In node.js mysql2 case, execute is used as prepared statement.
but In this repo, method execute is same with method query.
I might guess, It's not completed yet. Is it right?

Thanks to read. :)

added question: What is @ignore(wrapped comments) means exactly?

**Comment by manyuanrong** [comment]
Yes, because query is more general. Prepared statement is more efficient in some scenarios and can prevent SQL injection. deno_mysql will be better if it supports optional prepared statement.

In addition, /** @igonre ** / is used to identify that TS doc does not generate documents

**Comment by magichim** [comment]
@manyuanrong Thank to replay. I'll try to upgrade deno_mysql :).
