### ISSUE TITLE
CI was failed because of DB connection

### ISSUE THREAD

**Issue by t-yng** [manyuanrong/deno_mysql#34]
CI tests are failed with Database connection.

<img width="560" alt="スクリーンショット 2020-04-07 23 46 06" src="https://user-images.githubusercontent.com/11068883/78683213-fa689780-7929-11ea-8d72-83a998e3de0f.png">

**Comment by t-yng** [comment]
Maybe this is asynchronous database wakeup in docker container.

I tried to waiting for connection database.
https://github.com/t-yng/deno_mysql/actions/runs/72778009

**Comment by magichim** [comment]
Thank you your commit, however I have a question. What is difference before with your request? I think it's same.

**Comment by t-yng** [comment]
@magichim 
Thank you comment.
Sorry, What Do you point at "difference before with your request" ?

**Comment by t-yng** [comment]
If you pointed at "request" is this pull request #35 , it is same.
I think i should create issues when make pull request, but it is duplicated i will close this issues.

I will write problem in pull request.

**Comment by magichim** [comment]
I mean your code also is failed when mysql is still shutdown? and then might get same message. how can I check your code for testing env? Need docker env? If this asking is  foolish quesiton, Im really sorry... haha

**Comment by t-yng** [comment]
My fix is guarantee for MySQL is not shutdown.

I think now test workflow is sleep 10 seconds to wait mysql start up.
But the start up is over 10 seconds, database connection will be failed.
This is because MySQL server is finished to start up is after docker container is created and It action is asynchronous.

My fix is checking MySQL is finished to start up finish by connecting to the Database.
If it fail to connect, it will retry to check database connection for confirm MySQL is finished to start up.

After success database connection, some tests are executed.

I checked my code in local following command.

```
docker run -d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true mysql:latest; ./.github/workflows/wait-for-mysql.sh; deno run --allow-all ./test.ts;
```

And I checked CI in my forked repository.
* https://github.com/t-yng/deno_mysql/actions/runs/72778009
* https://github.com/t-yng/deno_mysql/actions/runs/72785800

Maybe This is lack of checking my code.

> If this asking is foolish quesiton, Im really sorry... haha
This is same for my saying... 😄

Please point out if I saying something strange.

**Comment by t-yng** [comment]
Maybe these articles are help my explanation.

* [Docker: Wait until MySQL is available](https://cweiske.de/tagebuch/docker-mysql-available.htm)
* [Docker Compose Wait for MySQL Container to be Ready: Easy Solution \- Datanovia](https://www.datanovia.com/en/lessons/docker-compose-wait-for-container-using-wait-tool/docker-compose-wait-for-mysql-container-to-be-ready/)

**Comment by manyuanrong** [comment]
Your PR effectively solved my problem. I originally thought that the connection could be established through `Deno.connect` and no exception was obtained, which means that mysql is ready. It seems that I was wrong.

**Comment by t-yng** [comment]
It is complecated for Docker MySQL container...

Thank you accept my PR. 😀
