### ISSUE TITLE
Support for "WHERE IN (?)" clause?

### ISSUE THREAD

**Issue by uki00a** [manyuanrong/deno_mysql#36]
## Summary

Hi, Thanks for creating this module!

When using "WHERE IN (?)" clause, an error (_"Operand should contain 1 column(s)"_) occurs.

Do you have any plans/ideas to support it?

Thanks!

## Steps to reproduce

- deno_mysql@1.7.0
- deno@v0.39.0

**mod.ts**

```typescript
import { Client } from "https://deno.land/x/mysql@1.7.0/mod.ts";

const client = await new Client().connect({
  hostname: "localhost",
  port: 3306,
  username: "test",
  db: "test",
  password: "test",
});

const sql = "SELECT * FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE `SCHEMA_NAME` IN (?)";
const params = [["test", "information_schema"]];
await client.query(sql, params);
```

When I run mod.ts, the following error occurs:

```
$ deno run --allow-net ./mod.ts
INFO connecting localhost:3306
INFO connected to localhost
error: Uncaught Error: Operand should contain 1 column(s)
► connection.ts:91:17

91           throw new Error(error.message);
                   ^

    at nextPacket (connection.ts:91:17)
```

**Comment by manyuanrong** [comment]
You should not add extra parentheses
https://github.com/manyuanrong/sql-builder/blob/master/test/util.ts
```ts
const sql = "select * from users where id in ?";
let result = await client.query(sql, [[1, 2, 3]]);
console.log(result);
```
![image](https://user-images.githubusercontent.com/7514524/80296689-b42b8900-87af-11ea-8034-7840d3ff2f3c.png)

**Comment by uki00a** [comment]
@manyuanrong Thanks, that worked! I'll close this.
