### ISSUE TITLE
求解代码

### ISSUE THREAD

**Issue by runnerSnail** [manyuanrong/deno_mysql#4]
```typescript
        let fieldCount = receive.body.readEncodedLen();
        const fields: FieldInfo[] = [];
        while (fieldCount--) {
            const packet = await this.nextPacket();
            const field = parseField(packet.body);
            fields.push(field);
        }
        await this.nextPacket(); // EOF
        const rows = [];
        while (true) {
            receive = await this.nextPacket();
            if (receive.type === "EOF") {
                break;
            } else {
                const row = parseRow(receive.body, fields);
                rows.push(row);
            }
        }
        return { rows, fields };
    }
```
ok判断之后下面的这段代码是干嘛的
https://github.com/manyuanrong/deno_mysql/blob/20a103977d672a590b314a5dada3b92e1686330a/src/connection.ts#L100

**Comment by manyuanrong** [comment]
发送命令之后之后，返回的第一个数据包如果是OK数据包。就是执行的命令，返回命令影响的结果。否则就是查询结果集，就按照结果集的数据结构进行解析。

**Comment by runnerSnail** [comment]
可以这样理解吗 ok数据包是类似update，delete这种执行的操作。result等就是query的结果集

**Comment by manyuanrong** [comment]
是的

**Comment by runnerSnail** [comment]
![image](https://user-images.githubusercontent.com/40654631/57314401-254bd980-7124-11e9-8f6e-35a5b0c70e60.png)
读到的数据可以打印出来，但是test报错。

**Comment by manyuanrong** [comment]
返回的还是空数组，没有解析出记录。

**Comment by runnerSnail** [comment]
![image](https://user-images.githubusercontent.com/40654631/57314814-f8e48d00-7124-11e9-9dbe-01a78b239d76.png)
我是一点点打印的 请问你是怎么调试的😄

**Comment by runnerSnail** [comment]
vscode可以调试吗

**Comment by manyuanrong** [comment]
vscode 安装 Deno VS Code Extension Pack 插件包

**Comment by manyuanrong** [comment]
![图片](https://user-images.githubusercontent.com/7514524/57315097-790af280-7125-11e9-94f3-ff3e57f09a74.png)
