### ISSUE TITLE
sha256 issue

### ISSUE THREAD

**Issue by Machock** [manyuanrong/deno_mysql#43]
**Uncaught Http: error sending request for url (https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/mod.ts): error trying to connect: dns error: 请求的名称有效，但是找不到请求的类型的数据。 (os error 11004)**

May you help me?

**Comment by manyuanrong** [comment]
I cannot speculate on the cause of the problem through your short description

**Comment by Machock** [comment]
When I use mysql, **import { Client } from "https://deno.land/x/mysql/mod.ts";**

then run the Deno program, will get an error as below:

Download https://denopkg.com/chiefbiiko/sha256@v1.0.2/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/mod.ts
error: Uncaught Http: error sending request for url (https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/mod.ts): error trying to connect: dns error: 
请求的名称有效，但是找不到请求的类型的数据。 (os error 11004)

**Comment by manyuanrong** [comment]
Can you directly access https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/mod.ts ？

**Comment by manyuanrong** [comment]
And what version of Deno you are using？

**Comment by Machock** [comment]
I can not open this link, https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/mod.ts

Deno version: 1.0.0-rc2

**Comment by manyuanrong** [comment]
It looks like your network environment is inaccessible

**Comment by Machock** [comment]
Yes, the root cause is the network, Thanks for ur help
