### ISSUE TITLE
Consider add label with prefix `v`?

### ISSUE THREAD

**Issue by wenjoy** [manyuanrong/deno_mysql#51]
tag like `v0.0.1` should be a good practice, i go through the offical modlue repo, most module follow this.

**Comment by manyuanrong** [comment]
thanks, I will

**Comment by manyuanrong** [comment]
@wenjoy I want to add you as a collaborator. Are you interested in participating together?

**Comment by wenjoy** [comment]
It's a honor. Thanks.

**Comment by wenjoy** [comment]
I'd like close this issue.
