### ISSUE TITLE
error : ConnectionReset: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by SquareMesh** [manyuanrong/deno_mysql#55]
Using deno_mysql in conjunction with oak for developing CRUD api against MySql db.  Application is able to initiate connection and serve multiple client.execute(getQuery) requests with no problem.  

However, if no requests are undertaken within 10 minute window the next call to client.execute(getQuery) fails, an immediate 2nd call also falls and then on a 3rd call the connection is established and continues to work as normal.

The following error is caught :-

Error: An existing connection was forcibly closed by the remote host. (os error 10054) 
    at SendPacket.send (https://deno.land/x/mysql/src/packets/packet.ts:30:13)
    at async Connection.execute (https://deno.land/x/mysql/src/connection.ts:161:5)
    at async https://deno.land/x/mysql/src/client.ts:101:14
    at async Client.useConnection (https://deno.land/x/mysql/src/client.ts:111:22)
    at async Client.execute (https://deno.land/x/mysql/src/client.ts:100:12)
    at async getCodeLookups (file:///C:/Users/Ian%20Strange%20-%20T1/Documents/GitHub/deno-auth/controllers/codelookup_controller.ts:16:3)
    at async allowedMethods (https://deno.land/x/oak@v5.2.0/router.ts:484:7)
    at async Application.#handleRequest (https://deno.land/x/oak@v5.2.0/application.ts:218:9)

On the 3rd call the client provides INFO messages to show reestablishing of connection 

INFO connecting 127.0.0.1:3306
INFO connected to 127.0.0.1

Have been experiencing this issue without realising the nature of the error for at least 2 weeks - and only today have looked further and discovered the connection issue.

I'm unsure if this an issue with deno_mysql or if its an issue with Deno.Conn.  

Is it possible to config around this? Or does deno_mysql need to change to cope with this timeout event and re-establish connection without error.

Let me know if you need any further info.

**Comment by manyuanrong** [comment]
This is because the mysql server will disconnect from the client after a period of time, causing the client to time out when sending the request again. Due to the unilateral termination of the connection by the server, I do not know how to receive the message that the connection is closed in Deno, so the current possible solution is to not use the connection pool and cache the connection. Or periodically send heartbeat packets to maintain the connection

**Comment by SquareMesh** [comment]
Thanks for reply.  Understand the connection timeout issue and can confirm that connection has default timeout of 600 seconds.

Are your thoughts on solution (i.e. maintain heartbeat packets) for application to implement ?

Thinking out aloud, I guess that deno_mysql should honor timeout invoked by mysql and not work around it and user wishing to go beyond needs to send command such as SET SESSION wait_timeout = 999999;  if they wish to keep alive longer - although timeout still needs to be managed.

Alternatively, in using deno-mysql for perpetual back-end web-service would it be worthwhile for deno_mysql to consider enhancement for a keep-connection-alive option and maintain its own heartbeat?

Out of curiosity what is causing connection to restablish on 3rd attempt?  And, could this potentially be used with a retry-timeout default of 3 attempts based on error raised?
